repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint src
        language: node
        additional_dependencies:
          - eslint@^10.5.0
          - typescript-eslint@^8.61.1
          - typescript@^6.0.3
          - '@types/vscode@^1.137.0'
        pass_filenames: false
        files: ^src/
      - id: check-types
        name: check-types
        entry: npx tsc --noEmit
        language: node
        additional_dependencies:
          - typescript@^6.0.3
          - '@types/vscode@^1.137.0'
          - '@types/node@24.x'
          - '@types/mocha@^10.0.10'
        pass_filenames: false
        files: ^src/
